name: Build, test, package

on: [push,pull_request, workflow_dispatch]

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.0

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@main
    with:
      itk-wheel-tag: 'v6.0rc01.dev20260915'
      itk-python-package-org: 'BRAINSia'
      itk-python-package-tag: 'itk6-build-system-v2'
      python3-minor-versions: '["11"]'
      manylinux-platforms: '["_2_28-x64"]'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
